apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: ms-config-server-k8s-deployment
spec:
  selector:
    matchLabels:
      app: ms-config-server-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: ms-config-server-k8s
    spec:
      containers:
        - name: ms-config-server-k8s
          image: sanjibkoleycts/ms-config-server # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: ms-config-server-k8ssvc
spec:
  selector:
    app: ms-config-server-k8s
  ports:
    - protocol: "TCP"
      port: 8888 # The port that the service is running on in the cluster
      targetPort: 8888 # The port exposed by the service
  type: NodePort # type of the service.